apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-client-root
  labels:
    type: local
spec:
  storageClassName: managed-nfs-storage
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.240.34
    path: /srv/nfs/kubedata